"""changed farmer id to be nullable

Revision ID: 417cd032922d
Revises: ab3461aa9212
Create Date: 2025-02-02 01:20:08.972484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417cd032922d'
down_revision = 'ab3461aa9212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('farmer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('farmer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
